[project]
name = "make-certificate-chain"
authors = [
    {name = "Jacky Chen"}
]
description = "Resolve the certificate chain from X.509 PEM or DER Certificate."
readme = "README.rst"
license = {text = "MIT"}
requires-python = ">=3.10"
classifiers = [
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Security :: Cryptography",
    "Topic :: Utilities"
]
dependencies = [
    "boto3>=1.42.38",
    "certifi>=2026.1.4",
    "click>=8.1.8",
    "cryptography>=46.0.4",
    "google-cloud-compute>=1.43.0",
    "google-cloud-certificate-manager>=1.12.0",
    "requests>=2.32.5",
]
dynamic = [
    "version"
]

[project.optional-dependencies]
dev = [
    "coverage>=7.13.2",
    "pip_audit>=2.9.0",
    "pytest>=9.0.2",
    "semgrep>=1.150.0; python_version>='3.10' and sys_platform == 'linux'"
]

[project.scripts]
mkcertchain = "make_certificate_chain.__main__:main"

[project.urls]
repository = "https://github.com/jacky9813/make-certificate-chain"

[build-system]
requires = [
    "setuptools>=65.0.0",
    "setuptools-scm[toml]>=8.1.0"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.setuptools.package-dir]
make_certificate_chain = "make_certificate_chain"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::cryptography.utils.CryptographyDeprecationWarning"
]